### ISSUE TITLE
Search across regs when in eregs

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#114]
Currently the eregs viewer has a core limitation where search only searches across the current regulation.  However, given we have built out an integrated search *prior* to viewing eregs, this limitation would be confusing once the user is within the regulations.

The goal of this story is 2 fold:
* Provide functionality that allows the user to search across regulations while viewing the regulations (i.e. are in the eregs viewer).
* Limit effort to be expended

<s>**Option 1:**
State: The user is viewing eregs [viewing eregs](https://gsa.invisionapp.com/share/NP7IRPOWD#/screens/163806594)
Trigger: The user clicks on the search icon in eregs
Outcome:
* The search fields are shown on the left nav
* The [eregs being viewed are still visible](https://gsa.invisionapp.com/share/NP7IRPOWD#/screens/163806586)
** Once the user enters a search term, then the screen displays results across regulations (identical to the ["show all results" for a Regulations search](https://gsa.invisionapp.com/share/NP7IRPOWD#/screens/163806599)</s>

<s> **Option 2: Leverage search in breadcrumbs bar.**
When searching across regs we have a breadcrumbs bar with a search field [(defaulted to search across Regulations)](https://fec-stage-proxy.18f.gov/data/legal/search/?search_type=regulations&search=president)</s>

<s> State: The user is [viewing eregs](https://gsa.invisionapp.com/share/NP7IRPOWD#/screens/163806594)
* The search tab in the eregs nav is hidden.
* However, the breadcrumb with the search field, however, is visible.
Trigger: User enters a search term in the breadcrumbs search.
Outcome: The user is brought to the ["show all results" for Regulations search](https://gsa.invisionapp.com/share/NP7IRPOWD#/screens/163806599)</s>

<s> The drawback to Option 2 from a users perspective is that the initial search (from the breadcrumbs search control) would not support faceting.  There'd be an extra click to search by facets. </s>

**Option 3**
We will hide all the tabs in the eregs viewer.  In other words search will not be directly accessible while the user is viewing a regulation (see comments below as to why).

![image](https://cloud.githubusercontent.com/assets/16668007/15910918/d9c6608e-2d92-11e6-899f-fa840efd48ea.png)

Notes: 
* #126 will add a search field on the initial landing page of eregs (that lists all the different parts/regulations)
* By getting rid of these controls, it should also address the potential user confusion of 2 hamburger menus in mobile stated in #117 as now the second hamburger menu should be hidden.

**Comment by edmullen** [comment]
After further consideration and a conversation with @jenniferthibault, I want to recommend a third option which we somewhat talked through in sprint planning. 

### Option 3
**Remove search within the eregs app all together, requiring people to go back (into the web app) to refine their search.** 

![image](https://cloud.githubusercontent.com/assets/2654503/15900288/f8d16e40-2d6c-11e6-90c8-16f6b5178923.png)


There is precedent for this recommendation. 

ADVISORY OPINIONS
When you are at the _item level_ -- I'm intentionally avoiding the word document because I'm uncertain about the elesticsearch parlance -- you are not given the option to search from within the page. This is intentional as you may have arrived from either the _all sources search_ or the _AO only search_.

![image](https://cloud.githubusercontent.com/assets/2654503/15899862/349ed70c-2d6b-11e6-9b2f-6059e3cb891f.png)

MATTERS UNDER REVIEW
MURs follow the same pattern. When you are looking at a canonical page, you cannot begin a search for a different MUR. You must go back to the previous page or up to the top level MUR page. I am comfortable with this slight burden.

![image](https://cloud.githubusercontent.com/assets/2654503/15900054/003927dc-2d6c-11e6-8c9a-058bd0bc5836.png)

WHY 

- least amount of effort
- aligns with other established patterns on legal
- fits what's been built so far
- simplifies the side panel when in eregs app because you do not need any tabs, just the single table of content view 
   - (which also means we can remove the tabs on mobile including the second table of content hamburger-like icon)
- easy to support during upgrades of the eregs platform

**Comment by porta-antiporta** [comment]
My thoughts:

* @anthonygarvan @adborden Can you confirm the effort required to hide those tabs?
* I like the resulting consistency of this approach
* Legal is consistently missing an easy way to start a search once the user is _at the item level_ (so we should create a to validate whether we need it, and where would it reside)

**Comment by edmullen** [comment]
On your last point @porta, I don't think the non-existence of search at the _item level_ is negative. In most cases I believe actual users will be arriving at the canonical AO, canonical mur, or Reg section from either an _all source search_ or a _type-specific_ search page. People are likely to set up a search, check out a result, and go back to the search if the thing they're looking at isn't right. Others may arrive here through a cross-reference and thus are not in searching mode, per se. 

I don't think we should assume there is a need for it until usage shows there is one.

**Comment by porta-antiporta** [comment]
ergh... typo in my last comment 

> Legal is consistently missing an easy way to start a search once the user is at the item level (so we should create a _test_ to validate whether we need it, and where would it reside)

i.e. Agree that we can't assume search needed once viewing an item; but proposing we architect a test to validate.

**Comment by adborden** [comment]
In my opinion, the level of effort to remove those tabs is small.
- Remove the tabs from the markup.
- Adjust the CSS to account for the new offsets of the collapsed menu.
- Remove the two-color assets.
