### ISSUE TITLE
Update regs body styles

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#123]
This refers to styling updates for eRegs aside from the FEC header, breadcrumb/subhead, and mobile. Will add details.

**Comment by adborden** [comment]
Just to call out some specifics, here's the [relevant invision screen](https://gsa.invisionapp.com/share/9Q710V45R#/screens/152289930).
- [ ] drawer toggle should be X instead of <
- [ ] right sidebar accordian
- [ ] footer next/previous icons and typography

**Comment by jenniferthibault** [comment]
## Feedback on the Regulations landing page
https://beta.fec.gov/regulations/

I've tried to piece out specific changes, but these will likely be easiest for @adborden and I to implement while pairing. 

@noahmanger do you have any recommendations for implementation, based on your experience with the patterns on the data tables?

### Search panel:
- [ ] Search panel is ~1 column too narrow. Width should be equal to width settings in the data table filter panels
![screen shot 2016-07-12 at 11 39 49 am](https://cloud.githubusercontent.com/assets/11636908/16773283/611dc00c-4825-11e6-9675-1b45412d1d9c.png)
 - [ ] `Search regulations` should be h2 style class: Text should be flushed left, not centered
 - [ ]  `Search regulations` should not be followed by an underline
![screen shot 2016-07-12 at 11 44 22 am](https://cloud.githubusercontent.com/assets/11636908/16773448/038a16c4-4826-11e6-9f1a-1b4060f8a74c.png)
 - [ ]  The search panel container should reach the bottom of the screen at all times.
 
![screen shot 2016-07-12 at 1 31 06 pm](https://cloud.githubusercontent.com/assets/11636908/16776799/fe40a660-4834-11e6-8a84-98609b0eedf0.png)

### Body results area
 - [ ] `Regulations` should use h1 styling to match the data tables. 
I think the regulations should each take up less visual/vertical space. Things are feeling bloated right now, and we can puff them down. This is going to be a combination of changes
 - [ ] Use `h3` heading styles for Regulation titles (like in [reg/reporting](https://beta.fec.gov/registration-and-reporting/)) . It's probably ok to leave the numerals as Karla (sans serif), but I think we should also bring the text size down
- [ ] Create specific width for numeral space, so that text doesn't jump in alignment based on numeral characters
  
![screen shot 2016-07-12 at 12 23 09 pm](https://cloud.githubusercontent.com/assets/11636908/16774758/7bf2c188-482b-11e6-8b87-21afe0934979.png)

- [ ] Remove the minimum height on the regulation column, in favor of letting the text dictate length with a margin-top / -bottom. Or—whatever the tactic— the goal is to ensure that single-line titles can take up less space than their two and three line partners.
  
![screen shot 2016-07-12 at 12 28 01 pm](https://cloud.githubusercontent.com/assets/11636908/16774927/1e113abc-482c-11e6-834d-f933f95b98d5.png)

- [ ] Use the `arrow-right-circle` icon in `gray` : https://pages.18f.gov/fec-style/section-icons.html
![screen shot 2016-07-12 at 1 22 32 pm](https://cloud.githubusercontent.com/assets/11636908/16776533/b93dfd2a-4833-11e6-8742-314e1002b26f.png)
![screen shot 2016-07-12 at 1 19 42 pm](https://cloud.githubusercontent.com/assets/11636908/16776573/f9e14c88-4833-11e6-878c-5318fd881732.png)

_________

Separate visual design task that I'll move into another issue:
- Make it more clear that "About eRegulations" is not about the Regulations, but about the platform, or tool.

**Comment by jenniferthibault** [comment]
A follow-up I just noticed on the search panel: it's less about the width and more about how it responds to the screen being resized, in a way that's consistent with how it's been implemented on the data side. I would expect them to behave in the same way:

![p0qoqfkcei](https://cloud.githubusercontent.com/assets/11636908/16778111/75b83ad2-483a-11e6-9625-f4cbd3b034f6.gif)

**Comment by jenniferthibault** [comment]
Next steps for this are to also audit the styles on an individual regulation page, and mark suggestions in this issue. Then @adborden and I will pair through implementation later when he's back from vacation.

**Comment by jenniferthibault** [comment]
Trying a new format for the feedback on an individual regulation page (h/t the layout in [this Sketch plugin](https://github.com/marcosvidal/Sketch-Notebook)) . The design below is my proposed revised styles, with annotations showing what's changing. I recommend clicking the image to open it in a new tab in order to view it at a legible size.

**Panel open:**

![regulations-audit-open](https://cloud.githubusercontent.com/assets/11636908/16999538/7e5d9a30-4e8c-11e6-993e-49ebf537c601.png)

**Panel closed**

<img width="440" alt="screen shot 2016-07-20 at 3 14 20 pm" src="https://cloud.githubusercontent.com/assets/11636908/16999576/aea3338a-4e8c-11e6-915d-1bed955be9b6.png">



Next steps: When Aaron is back, pair to determine what's possible.

**Comment by adborden** [comment]
As per @porta-antiporta, we're going to break this story up into smaller stories. He asked that I comment on the effort involved.

I think this all looks great and is pretty straight forward and easy to do. I would recommend breaking up the stories by component and each story would be roughly 1 point, with 10-15 stories total. The trickiest bits are the icons, which will require a little spacing adjustment to make sure they are centered and fit properly. The TOC icon on the panel is the trickiest thing, because it's position moves when the panel open/closes. I think it's worth doing, but maybe put that story last.

**Comment by jenniferthibault** [comment]
@adborden the updated filter panel layout design you were seeing in the AO search mockups in https://github.com/18F/fec-eregs/issues/186#issuecomment-235298380 are documented for implementation on the data side in this issue: https://github.com/18F/openFEC-web-app/issues/1379

When you are ready to tackle the filter panel changes, it will likely be helpful to follow progress on that issue.

**Comment by jenniferthibault** [comment]
I'm starting to break these out & will crosslink to this original issue.

**Comment by jenniferthibault** [comment]
K! @porta-antiporta since these are now all broken out, is it ok to close this issue?

**Comment by porta-antiporta** [comment]
thank you @jenniferthibault!
