### ISSUE TITLE
Legal resources landing page does not highlight Legal resources nav

### ISSUE THREAD

**Issue by adborden** [18F/fec-eregs#170]
![screenshot from 2016-07-07 16-02-12](https://cloud.githubusercontent.com/assets/509703/16672646/44dfe536-445c-11e6-8d5c-3d7e40d80c1f.png)

You should see the `.is-parent` class on the nav item so you know what content section you're in.

**Comment by porta-antiporta** [comment]
This is not just the legal-resources landing page but all subsequent pages (search results, canonicals, ao/statute landing page).  

Regulations is correct, but that's because we are in a separate app and just pin `is-parent` to legal resources in the eregs FEC header.

The current implementation in `fec-cms` defines a `self.content_section` to decide where to display the highlight.  However, only registration-reporting actually uses that.  The return values seem to be defined in `models.py` but unsure how to tie those return values to self.content_section.

The current implementation in `openFEC-web-app` simply pins it to Campaign Finance in `navigation.html`.

**Comment by porta-antiporta** [comment]
Paired with @adborden on this.  There will need to be two fixes, one for `fec-cms` and one for `openFEC-web-app`.

**fec-cms**
Will need to migrate the current legal resources html page to a wagtail template so that we can determine the context.

**openFEC-web-app**
Flask has a concept of _context_ that we will need to implement to be able to distinguish between campaign finance and legal resources related pages.

**Comment by porta-antiporta** [comment]
Deprioritizing this story ATM for MURs and handoff activities.

**Comment by noahmanger** [comment]
This was implemented in https://github.com/18F/openFEC-web-app/issues/1724 and shipped.
