### ISSUE TITLE
Presentation:  CFR conventions

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#18]
Subsections are designated throughout by the subsection letter/number followed by a period -- CFR convention is to put the letter/number within parens. Similarly, on the main TOC, the Title is labeled "Title XI" -- that should be "Title 11" per CFR convention.

**Comment by porta-antiporta** [comment]
@PaulClark2 just to clarify 114.3(c)(2)(iv) should be (114.3)(c)(2)(iv).  Is that correct?

**Comment by porta-antiporta** [comment]
Or maybe not.   

![screen shot 2016-03-08 at 2 37 56 pm](https://cloud.githubusercontent.com/assets/16668007/13615541/6f5c2d04-e53b-11e5-9281-5f9754a7b45b.png)

![screen shot 2016-03-08 at 2 40 55 pm](https://cloud.githubusercontent.com/assets/16668007/13615595/d39e21b4-e53b-11e5-9582-aab565c24130.png)

The conventions seem to be consistent 11 CFR 114.1(a)(2)(i)?

**Comment by cmc333333** [comment]
I'm guessing the concern is that those are displayed as 
```
4.
    i.
   ii.
  iii.
```
Rather than
```
(4)
    (i)
   (ii)
  (iii)
```

We originally used the period notation as we found that to be more readable for end users (it's also more in line with semantic HTML). However, we recently added the ability to use paren markers instead (though our use case was for a limited portion of the regulation).

@porta-antiporta up to your team on which method makes sense, but if you want to go the paren route, you should just need to add a stylesheet which does something similar to `.paragraph-marker` as is currently done to `.stripped-marker`: https://github.com/18F/regulations-site/blob/master/regulations/static/regulations/css/less/module/paragraph-markers.less . We can discuss further if needed.

**Comment by PaulClark2** [comment]
@amykort Generally there are a number of formatting issues but I think there specific comment here was about the use of Roman numerals instead of Arabic.
![11 cfr](https://cloud.githubusercontent.com/assets/11817734/13620293/8f48101c-e55c-11e5-8eba-d9012cc06aee.png)

**Comment by AmyKort** [comment]
Yes, the specific comment was about the Title XI--should be Title 11. As a larger issue, I think that if the regulatory citation is something like 11 CFR 100.5 (g)(4)(ii)(J), then we were looking for the eRegs citation to be identically marked as far as the upper and lower case and parentheses use goes. Otherwise, it is easy to get lost.

**Comment by porta-antiporta** [comment]
reopening, closed accidentally
