### ISSUE TITLE
How do we represent hits within an AO from different docs

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#186]
https://gsa.invisionapp.com/share/AR7U3Y662#/screens/167711241

Need to show how we can display results from multiple document types within the same AO

**Comment by jenniferthibault** [comment]
While working on this, I simultaneously integrated a lot of the styling and interaction updates we've been making on the data side to more closely integrate with patterns for how results are returned when using filters.

Here's one way I was thinking we could handle this, with one guiding rule:
- If an AO has a Final opinion, and if that final opinion displays matches for the search term, always list the final opinion first. List the following documents by date, most recent first.

![ao-search-desktop-v2](https://cloud.githubusercontent.com/assets/11636908/17071447/9c3cc5f4-502f-11e6-9abb-5476ec63040f.png)


Mobile feels a little tougher to know what to highlight. On the data side, we've typically compressed the information down to one column, but there is often a details panel that makes it feel more successful. Here, what's your sense of which column to show & how/if to show the matching excerpts?

![ao-search-mobile-v2](https://cloud.githubusercontent.com/assets/11636908/17071497/d64cef62-502f-11e6-8733-eb37d93bb61c.png)


cc @porta-antiporta & @anthonygarvan

**Comment by porta-antiporta** [comment]
@jenniferthibault really digging the consistency with the rest of beta.  had a couple requests for the design to include:

- Final Opinion (and link to it) should be more prominent as a vast majority of the time that is the document folks are most interested in.
- Ability to collapse the AO documents into 1 (perhaps just showing the final opinion).  This gets us the real estate back to show more AOs.  Also will come in handy when we display results in the [integrated search (which shows results for AOs, Regs, Statutes, MURs etc)]{https://gsa.invisionapp.com/d/main#/console/7833288/171040671/preview}
- Was the reason for including a date column to provide feedback to the user who may be setting a date facet?  We'd have to clarify from @edmullen whether the date facet is meant to apply to when the AO was published or the date of the specific documents.

**Comment by jenniferthibault** [comment]
Thanks @porta-antiporta ! Really digging the consistency too. 

Based on your thoughts/questions, it may make sense for us to expand the pattern used by the [Calendar](https://beta.fec.gov/calendar/) which is friendlier for showing longer text-based results.  Combined with a mini accordion or toggle for the "view more", here's what that could look like with a few thoughts on your questions below it:

**Closed**

![ao-search-desktop-v2 copy 3](https://cloud.githubusercontent.com/assets/11636908/17119881/cb81a8fc-5296-11e6-85ad-c16317f86056.png)

**Open**

![ao-search-desktop-v2 copy 5](https://cloud.githubusercontent.com/assets/11636908/17119884/cdf5073c-5296-11e6-9a33-5213253255de.png)


- If the final opinion is the only doc we show on the closed panel, I wouldn't want to bump the visual prominence up too much, because that action could draw more attention than the actual text hits, which would be what clues folks in to what they're looking for or not. I totally hear why on the individual AO canonical page we want to make the Final Opinion really prominent, but here, I think it can stand down a little. (To be confirmed with testing)

- I did include the date column because it was a filter users can apply, so it seemed like you'd want that to be visible in the results. Would definitely be helpful to know what the date is dating though, and then perhaps specify the filter title to match

**Comment by edmullen** [comment]
**So far,** I was thinking that the date ranges in the facets would only be in years, not specific dates. FEC currently organizes AOs by year and there are not many each year. 2015 had just 16 AOs. 
![image](https://cloud.githubusercontent.com/assets/2654503/17140177/81f5e2a0-5315-11e6-8a47-4188c99545cf.png)
I haven't seen any evidence yet that filtering by year is insufficient. My tendency is to just support the yearly filtering by case date, until we see a need for the additional functionality. And I wouldn't support document date filter until we see there's a need. I don't _think_ there is a need.

**I like the second approach a lot,** the one borrowing from the calendar. I think it manages the "show more hits" functionality really well.

The one piece that feels a bit off is the AO summary, especially in the open state. The summary is a summary of the AO as a whole. It's not part of the Final Opinion. since the row is now being used to describe document-level items, it appears that it's describing the final opinion document rather than the case as a whole.

![image](https://cloud.githubusercontent.com/assets/2654503/17140124/47c519a2-5315-11e6-871f-6ecb898b8a63.png)

That said, I like how this is going and can see implications for the MURS, Regs, etc. One thing to keep in mind is that the AO individual result items can also reside on the _All Sources_ results page with other document types: https://gsa.invisionapp.com/share/NP7IRPOWD#/screens/163806583

**Comment by jenniferthibault** [comment]
Thanks for the clarification on the summary @edmullen ! I had been under the impression it was summarizing the final opinion, not the whole AO. I regrouped things a bit to better reflect that, and dropped the document year category. It looks like the filterable year can be inferred from the AO title.

I do see how this has implications for the other individual search pages, but thinking it _shouldn't_ yet change things on the All Sources results page, because you aren't using a faceted search interaction there.

**Closed**
![ao-search-desktop-v2 copy 8](https://cloud.githubusercontent.com/assets/11636908/17143194/98ffb0e2-5320-11e6-913e-dc9ac2874385.png)

**Open**
![ao-search-desktop-v2 copy 7](https://cloud.githubusercontent.com/assets/11636908/17143203/9e3f0922-5320-11e6-9a02-7711cd0a808e.png)

**Comment by porta-antiporta** [comment]
🎉

**Comment by porta-antiporta** [comment]
@jenniferthibault @edmullen if we are 👍 on the latest proposal, would like to present this at our next demo.

**Comment by porta-antiporta** [comment]
This story is split up into the following for implementation:
#191 - Roll up of individual docs into a single AO
#159 - Support document type facet
#162 - Support date and pending AO facet

**Comment by edmullen** [comment]
Sounds good to me.
