### ISSUE TITLE
Pages are blank when opening new regs

### ISSUE THREAD

**Issue by wslack** [18F/fec-eregs#198]
When I open https://beta.fec.gov/regulations/108 and see a blank page, it's hard to know that I need to click a link in the left hand menu. For example, the link on https://epa-notice.usa.gov/ paints straight to part 1.1 of a regulation.

I looked for another issue but didn't see it; please close if duplicate!

(edited by @porta-antiporta) TO DO: 
- [ ] Refer to thread on #134.
- [ ] Work with content and FEC OGC to get approved language that can be used for all FEC regulations' `landing pages` (beta.fec.gov/regulations/<integer-regulation-number>
- [ ] Update the landing page to reflect the approved content

**Comment by wslack** [comment]
This might be covered by https://github.com/18F/fec-eregs/issues/196 - @porta-antiporta can say for sure.

**Comment by porta-antiporta** [comment]
@wslack #196 is regarding AOs. 

The issue you point out is a known gap currently.  The issue is that the `landing page` for each regulation can have text which is currently empty.  See the thread on #134 for more commentary.

I could not find an issue tracking the creation of generic text for regulation `landing page` on FEC so we will track it under this issue.
