### ISSUE TITLE
Create Enforcement Matters Landing Page

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#224]
Implement landing page per the following mockup:

https://gsa.invisionapp.com/share/S58HMFKMB#/185960393_Enforcement

- [x] Only implement the sections decided by content on #233
- [x] Discuss in planning whether "recently closed cases" is available in the API.  If not, move to a different story.
     - Recently closed cases will be part of a later story - Porta to log and tie to this one.

**Comment by porta-antiporta** [comment]
@jenniferthibault : noticed the mockup has the search field on the right (instead of left like ao's, statutes, regulations)  Is this intended for Enforcement only, or all?

**Comment by jenniferthibault** [comment]
@porta-antiporta I'm going to carry that question over to be answered in the design issue, #242

**Comment by jenniferthibault** [comment]
Visual designs were discussed and completed in #242 
[Desktop mockups](https://gsa.invisionapp.com/share/S58HMFKMB#/185960393_Enforcement)
[Mobile mockups ](https://gsa.invisionapp.com/share/MA8ID5U6Z#/189405400_Enforcement_Landing_Mobile)

Content in https://github.com/18F/fec-eregs/issues/233 is still in progress. I'm glad to update the mockups once content is finalized so that everything is accurate.

**Comment by adborden** [comment]
Fixed in https://github.com/18F/openFEC-web-app/issues/1604
