### ISSUE TITLE
Question:  What definitions are "best viewed in original location?"

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#23]
Clicking on some linked definitions pulls up a window that says that the definition is "best viewed in original location" -- how it is determined which definitions produce this statement?

**Comment by porta-antiporta** [comment]
@PaulClark2 That shows up when the definition itself is several lines/paragraphs long.  For example: https://fec-eregs.apps.cloud.gov/114-8/2015-annual-114#114-8-e.

If you look at the definition for `executive or administrative personnel` the definition itself is very long.  So rather than displaying that in the right hand section; there's a link to the location in the regulation that's defining that term.

**Comment by porta-antiporta** [comment]
Will demo an enhancement in the latest version that pulls the initial description of a long definition before providing the link to the section itself.
