### ISSUE TITLE
Enforcement landing: Legal resources sidebar

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-eregs#282]
FEC's Office of General Counsel approved content for the enforcement landing with a list of accompanying legal resources. We need to incorporate them into the design before we release the content.

This is how we've handled legal resources in the `Registration and reporting` section, but I'm not sure how we want to handle it here:

<img width="1083" alt="screen shot 2016-10-05 at 4 16 55 pm" src="https://cloud.githubusercontent.com/assets/10552702/19131976/31276558-8b17-11e6-9807-fbe7365f19dc.png">

These are the legal resources for inclusion on the enforcement landing page:
> 11 CFR 111.21
> 11 CFR 111.24
> 11 CFR 111.31
> 11 CFR 111.20-111.24

calling in @jenniferthibault and @adborden to collaborate!

**Comment by jenniferthibault** [comment]
Thanks @emileighoutlaw — In order to find the right format for these, I'd like to understand a bit about what these citations are and how people use them. (aka: the good ol' "what's the use case here?") 

Do you know if we can provide the few word summary of what each reference is, like we've done in the example you've provided?

**Comment by emileighoutlaw** [comment]
Hello! Absolutely! The use case here is that lawyers, committee staff, and researchers may want to explore the full-text laws from which this introductory, plain language text was drawn. 

And I wholeheartedly agree that we should include the title of the regulations with the numbers. I just hadn't yet hunted down all the links and titles. What we'd end up with would look like this:

> **Legal resources**
Read the regulations that apply to this page:

> [11 CFR 111.21](https://www.gpo.gov/fdsys/granule/CFR-1997-title11-vol1/CFR-1997-title11-vol1-sec111-21/content-detail.html)
_Confidentiality_

> [11 CFR 111.24](https://www.gpo.gov/fdsys/search/pagedetails.action?st=11+CFR+111.24&granuleId=CFR-2016-title11-vol1-sec111-24&packageId=CFR-2016-title11-vol1&fromState=)
_Civil penalties_

> [11 CFR 111.31](https://www.gpo.gov/fdsys/search/pagedetails.action?st=11+CFR+111.31&granuleId=CFR-2016-title11-vol1-sec111-31&packageId=CFR-2016-title11-vol1&fromState=)
Administrative fines

> [11 CFR 111.20](https://www.gpo.gov/fdsys/search/pagedetails.action?na=&se=&sm=&flr=&ercode=&dateBrowse=&govAuthBrowse=&collection=&historical=false&st=11+CFR+111.20&psh=&sbh=&tfh=&originalSearch=&fromState=&sb=re&sb=re&ps=10&ps=10&granuleId=CFR-2016-title11-vol1-sec111-20&packageId=CFR-2016-title11-vol1)
_Public disclosure of Commission action_

>[11 CFR 111.21](https://www.gpo.gov/fdsys/search/pagedetails.action?st=11+CFR+111.21&granuleId=CFR-2016-title11-vol1-sec111-21&packageId=CFR-2016-title11-vol1&fromState=)
_Confidentiality_

> [11 CFR 111.22](https://www.gpo.gov/fdsys/search/pagedetails.action?st=11+CFR+111.22&granuleId=CFR-2016-title11-vol1-sec111-22&packageId=CFR-2016-title11-vol1&fromState=)
_Ex parte communications_

> 11 CFR [111.23](https://www.gpo.gov/fdsys/search/pagedetails.action?st=11+CFR+111.23&granuleId=CFR-2016-title11-vol1-sec111-23&packageId=CFR-2016-title11-vol1&fromState=)
_Representation by counsel; notification_

> [11 CFR 111.24](https://www.gpo.gov/fdsys/search/pagedetails.action?st=11+CFR+111.24&granuleId=CFR-2016-title11-vol1-sec111-24&packageId=CFR-2016-title11-vol1&fromState=)
_Civil penalties_

**Comment by porta-antiporta** [comment]
@emileighoutlaw were these citations `need in place to go live` type changes?  or they are ok with us going live without it and then adding them in the very next release?

@adrianwebb if the former, we may want to plan a mini-release (hotfix) mid sprint 24 once the implementation is ready so that we can launch MURs.  given we need time to design how these citations will be shown, we will not be able to get it in for sprint 23 unfortunately.

**Comment by porta-antiporta** [comment]
@jenniferthibault assigning you for the moment so that when you have the design ready, can just add it to this issue.

**Comment by porta-antiporta** [comment]
https://github.com/18F/openFEC-web-app/pull/1604#issuecomment-252037879 has the current implementation

**Comment by porta-antiporta** [comment]
interesting to note that http://www.fec.gov/em/em.shtml doesn't list the citations.  so perhaps we could go live with MURs without the citations? cc: @adrianwebb

**Comment by emileighoutlaw** [comment]
The citations are need in place to go live, I'm afraid, @porta-antiporta

**Comment by porta-antiporta** [comment]
understood @emileighoutlaw ... i may still make a pitch to our FEC partners though in the demo on tuesday ;)

**Comment by emileighoutlaw** [comment]
Definitely do that, @porta-antiporta !

**Comment by jenniferthibault** [comment]
Ok I have questions and I have good news 😸 

## Questions

@emileighoutlaw Looking at your content and links [above](https://github.com/18F/fec-eregs/issues/282#issuecomment-252008003) I think there may have been some copy/paste glitches, because some items are repeated in the list. 

- Are these the correct items? Or am I missing anything?
  - 11 CFR 111.20  _Public disclosure of Commission action_
  - 11 CFR 111.21  _Confidentiality_
  - 11 CFR 111.22  _Ex parte communications_
  - 11 CFR 111.23  _Representation by counsel; notification_
  - 11 CFR 111.24  _Civil penalties_
  - 11 CFR 111.31  _Administrative fines_

I also thought it might be logical to list the citations numerically, unless there is a better way to organize them that I'm not seeing in how they were.
- Is it ok to put them in numerical order, like I did above?

- Should the whole text [11 CFR 111.xx](#) be the link? Or should it be just the end part: 11 CFR [111.xx](#) ? This is relevant here, but also all over the site for consistency. 

- It seems a _smidge_ strange to me to call the sidebar `Legal resources` here, since it's inside the legal resources section. Is that weird? Or am I overthinking?

## And! The good news!

@adrianwebb / @porta-antiporta I think this will be able to make the release! 
I looked around a bit and considered a few options, but this landing page does indeed feel very close to the templates we use for the [Essentials pages](https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/) on the Registration and Reporting side (they are kind of the same level/role in the IA, just in different sections) and I think the sidebar _is_ the best pattern for here to start with.

I wanted to see if I could design it in the browser to be the most efficient, and I think I got it mostly there!  I'm submitting a PR https://github.com/18F/openFEC-web-app/pull/1622 that updates the design this far, and I'm hoping that I can pair with Noah or Aaron tomorrow to make a few final fine-tuned style adjustments to it. What do you think of the layout overall, @emileighoutlaw ?

![screencapture-127-0-0-1-3000-legal-enforcement-1475806583662](https://cloud.githubusercontent.com/assets/11636908/19177423/1601a8fa-8c17-11e6-9829-de4947170225.png)

**Comment by porta-antiporta** [comment]
You rock @jenniferthibault!

**Comment by jenniferthibault** [comment]
Closed by https://github.com/18F/openFEC-web-app/pull/1622
