### ISSUE TITLE
Refine MUR search ordering and general ease of search

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-eregs#297]
Comment: The results do not come up in any useful order.  In EQS, they come up in chronological order by case number which makes it easy to come back to a search after an interruption or break and it provides a broad indicator of the age of the case (before BCRA, for example).
 
Other useful ways to search:  I sometimes use the date searches in EQS if I want to find cases closed more recently. The ability to search particular types of documents: conciliation agreements, general counsel’s reports, statements of reason or to narrow a broader search to particular documents.

**Comment by nickykrause** [comment]
(cc: @jenniferthibault, @emileighoutlaw, @adrianwebb)
   
The design team just met to discuss the legal issues for this sprint, in order to remove any blockers from us, and here's a summary of our discussion on this issue:

We are thinking that this issue may not need to be resolved prior to release.

The problem seems to be that users don't have a clear sense of how the search results are determined, including how the display order works. Currently, the ordering of results is based on "relevance," but the users seem unable to assess whether or not the automated relevance calculation is indeed working (and how). 

The users' proposed solution is thus to return the results in chronological order, _as well as_ to be able to search particular types of documents.

Consequently, this issue appears to be multifaceted, and it seems related to issue #296 - "Help users better determine if the cases returned are relevant." We would be in favor of closing this issue and moving this "results ordering" conversation into #296.

**Comment by jenniferthibault** [comment]
Closing this issue in favor of #296 , where I have carried over the users' goal of refining returned results.
