### ISSUE TITLE
Enable users to search MURs by citations

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-eregs#303]
From FEC enforcement folks feedback in: https://github.com/18F/fec-eregs/issues/289 and split out from https://github.com/18F/fec-eregs/issues/295

On the current fec.gov, Archived MURs can be filtered/searched across by citation matches. I'm not sure if this functionality is also possible on fec.gov's EQS system for closed (current) MURs or not.

<img width="1061" alt="screen shot 2016-11-02 at 1 14 16 am" src="https://cloud.githubusercontent.com/assets/11636908/19917461/048777ac-a09a-11e6-90f6-3dc0472c3ed0.png">

Being able to link resources together in this way supports users in their quest to know if they've found _everything_ relevant to the area they're researching.

Grooming considerations:

- [x] Assess feasibility of filtering archived MURs and closed (current) MURs on betaFEC by citations referenced

**Comment by noahmanger** [comment]
During our grooming session this week we realized that we had more we need to figure out about how citations should work. As I understand it, the question on the table is:

Should searching by citation look within the text of documents, or only the meta data?

There's a few considerations on this front:
- When searching within the text, the results will likely be incomplete because of the way that citations can be written in multiple parts
- If we're talking about a search through text, then this capability basically already exists with the keyword search
- The reclassification mapping is only for citations in meta data, though I'm not sure if we can also do it for searching through text citations

I'm not sure who we need to get these answers from, so calling @amypike for help!

**Comment by noahmanger** [comment]
We now have separate issues for the back-end, front-end and design work for this, so I'm closing this issue.
