### ISSUE TITLE
Italicized headers appear in upper case and twice

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#7]
https://fec-eregs.apps.cloud.gov/100-5/2015-annual-100#100-5-d

![headers-in-caps-twice](https://cloud.githubusercontent.com/assets/11817734/13259956/8fb349f8-da27-11e5-911f-1775e3c7bc45.png)

**Comment by PaulClark2** [comment]
This might be similar to the issue discussed in https://github.com/18F/fec-eregs/issues/6.

Are "keyterms" in the eRegulations platform bold instead of italicized?   Even if that's intentional, the second occurrence probably should not be bold.  Can it be the same font as the text following the second occurrence or italicized like it is in the print version? 

@amykort do you have any thoughts about this?

**Comment by AmyKort** [comment]
There are instances in the regulations (mostly definitions) where the heading for the provision is italicized (or bold) and then the first words in the language of the provision itself are the same words as those in the heading and also italicized. In the printed version, usually the heading is on a separate line from the text of the provision. Sometimes it's not, in which case the terms are italicized twice across one line and pick right up with the language of the provision on that same line. In eRegs, it often treats both instances of the italicized or bolded term as a heading on a separate heading line, and then there's a line break, and the rest of the text of the provision picks up mid-sentence. So, there's a line with the heading big and in bold twice and a line break and then regular text that starts in the middle of a sentence--sort of like when you start your email in the subject line and then pick up where you left off in the text. I find this confusing in eRegs because the heading line repeats and looks like a mistake and it is not necessarily obvious that the terms from the heading are the ones that started the sentence you're reading.

**Comment by cmc333333** [comment]
Right; I'd bet the data source uses a single `<E>` spanning both the keyterm and the term immediately following. This wouldn't make a difference in the print version (since the text is all on one line), but does make a difference semantically.

@tadhg-ohiggins @anthonygarvan @annalee et al -- I'd recommend an FEC-specific preprocessor to split these `<E>`s up

**Comment by AmyKort** [comment]
I think this particular example is confusing in part because number 6 doesn't pick up where the heading left off. And then, the headings are huge, and when you get to section (F), whicb comes next, everything is very small, which is misleading because (f) is the point where you start something new. Compared to the printed version, the section pasted above skips language (in the printed version: (1) Principal campaign committee. Principal campaign committee means a political committee . . .  There's no line break at all in the printed version.

**Comment by AmyKort** [comment]
Thank you!! I'm just writing and writing and I wasn't sure whether I was making any sense!

**Comment by porta-antiporta** [comment]
@PaulClark2 Yes, this is the same root cause as #6.
