### ISSUE TITLE
Add "More hits" and canonical AO link to the AO section in the universal legal search

### ISSUE THREAD

**Issue by adborden** [18F/fec-eregs#76]
@edmullen I believe this is the behavior you're going for, please correct me if I'm wrong.

On the front end, we'll limit the number of hits displayed, and then "Display all hits" will expand to include all the snippets found. Currently the snippets are too short to be displayed on their own but #75 allows us to have longer snippet text.

![screenshot from 2016-04-27 18-50-51](https://cloud.githubusercontent.com/assets/509703/14873317/ce8780cc-0ca9-11e6-9c9d-4647b3a064cb.png)

**Comment by edmullen** [comment]
Yes, you are correct, but I'd like to change where the trigger to show more is located. I have been thinking about this as part of a reworking of the AO result. 

![ao result](https://cloud.githubusercontent.com/assets/2654503/14892266/0e2d888c-0d38-11e6-9b8b-c15dd03445f3.png)

Note in the image above that the "more hits" link is inline following the first snippet. This is because initial testing showed the "Display all hits" to be too prominent and sometime confused for different functionality.

When the user clicks the “more hits” link, we should load up to 6 additional excerpts. The mock only show 4 for space.) I’m not sure how many are truly useful. In this space we would need to limit the number displayed. I’d like to see if 7 total meets the need before creating a special view to accommodate more.

Are the hits weighted in any way?

@adborden Should I create a separate issue for the other aspects of the result item reworking? (moving requestor, adding Final Opinion, changing link of AO number once we have the canonical page in place)

**Comment by adborden** [comment]
> Are the hits weighted in any way?

Question for @anthonygarvan ^^

**Comment by adborden** [comment]
@edmullen no need for another ticket, I think this is a good chunk of related work. I'll change the title though.

**Comment by edmullen** [comment]
cc @jenniferthibault

**Comment by jenniferthibault** [comment]
Thinking on this— are we open to trying some different language for the "hits" link? From the sessions I've sat in on, the word "hit" seems like a term users aren't immediately associating with an interaction. What if we tried "more matches within this result" ? Or something similar that is more explicit about the more-ness being inside that same entry.

**Comment by porta-antiporta** [comment]
Think this is now duplicated to #187 where we have an updated design.  The implementation story is also linked to that issue.  Closing this one.
