### ISSUE TITLE
Missing italics

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#9]
https://fec-eregs.apps.cloud.gov/100-19/2015-annual-100#100-19-a

"file," filed" and "filing" are italicized in the print version of 11 CFR

![filed](https://cloud.githubusercontent.com/assets/11817734/13260238/9ddbcc66-da28-11e5-8f98-e428c81ce4b3.png)

**Comment by porta-antiporta** [comment]
https://trello.com/c/NxLmcWO8/24-fec-eregs-missing-italics

**Comment by tadhg-ohiggins** [comment]
This isn't really about italics; those are words that should be defined terms, but the language and structure used here simply doesn't fit in our current definition framework and would need substantial enhancement to address. I think we should do that, because the FEC are likely not the only agency to have these kinds of definitions, but it's not a minor tweak.

In addition, this raises the issue of how to handle cross-regulation definitions, also a feature eRegs currently doesn't have.

**Comment by porta-antiporta** [comment]
I think from a cost-benefit perspective, we can table this to a later time.

**Comment by tadhg-ohiggins** [comment]
Sure.

Adding links to https://github.com/eregs/regulations-parser/issues/246 and https://github.com/eregs/regulations-parser/issues/247 for future reference.

**Comment by AmyKort** [comment]
Sounds good!
